name: projects-porfidev
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
region: atl
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: porfidev-website
      match:
        authority:
          exact: ""
        path:
          prefix: /
services:
 - name: porfidev-website
   environment_slug: node-js
   source_dir: apps/porfidev-website
   instance_count: 1
   instance_size_slug: apps-s-1vcpu-0.5gb
   http_port: 8080
   envs:
     - key: NODE_ENV
       scope: RUN_AND_BUILD_TIME
       value: production
     - key: PORT
       scope: RUN_AND_BUILD_TIME
       value: "8080"
     - key: NODE_VERSION
       value: "20"
       scope: RUN_AND_BUILD_TIME
     - key: NPM_CONFIG_PRODUCTION
       value: "false"
       scope: BUILD_TIME
   build_command: >
     corepack enable &&
     corepack prepare pnpm@10.20.0 --activate &&
     pnpm i --frozen-lockfile &&
     pnpm exec patch-package || true &&
     pnpm build
   run_command: pnpm start
   github:
    branch: main
    deploy_on_push: true
    repo: porfidev/porfidev-projects


